### ISSUE TITLE
Strange `.fail.png` artifact on larger captures.

### ISSUE THREAD

**Issue by chris-dura** [Huddle/PhantomCSS#102]
I'm using PhantomCSS to generate responsive screen captures, and I'm witnessing a strange artifact in the `fail` images on my largest viewport which is 1800px.

The baseline and diff images are fine...
*Baseline*
![styleguide-spinner_40](https://cloud.githubusercontent.com/assets/3680914/6697920/b310d126-ccb9-11e4-98af-abf6875c9d56.png)
*Diff*
![styleguide-spinner_40 diff](https://cloud.githubusercontent.com/assets/3680914/6697919/b30ee06e-ccb9-11e4-91f3-7f0ea957c89e.png)

But the combined fail image has this grid pattern.
![styleguide-spinner_40 fail](https://cloud.githubusercontent.com/assets/3680914/6697944/d305a42a-ccb9-11e4-9d17-2873c5e048b0.png)

Zooming into the fail image in Photoshop shows that those pixels are transparent... almost like there's a 1px masking grid lines over the entire image.
![screen shot 2015-03-17 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/3680914/6697993/42b04622-ccba-11e4-9d3d-05478d65e0e9.png)

I wonder if there is a limitation to viewport size, either in PhantomJS/CasperJS, or perhaps one of the image libraries (Resemble, ImageMagick)? You would think that if it was a limitation of PhantomJS/CasperJS, the baseline and diff images would be screwy.

**Comment by jamescryer** [comment]
ImageMagick is not a dependency. This is performance mitigation by Resemble, it skips pixels on large images in order to provide faster feedback. See the bottom of the README https://github.com/Huddle/Resemble.js . I haven't noticed any loss of test coverage by this skipping.

You can switch it off like so

```
phantomcss.init({
   outputSettings: {
        largeImageThreshold: 0
    }
});
```

Though I'd recommend having a smaller visual test.

**Comment by chris-dura** [comment]
Thanks @jamescryer, that makes perfect sense... guess I should read the Resemble docs as well.

> Though I'd recommend having a smaller visual test.

Yeah, don't I know it... those 4K breakpoints are a $%#@! :smile:
