### ISSUE TITLE
Update PhantomJS Dependency

### ISSUE THREAD

**Issue by marcusvetter** [Huddle/PhantomCSS#106]
Would be nice if you could update the phantomjs dependency to ^1.9.8. Otherwise users have to include another phantomjs in version 1.9.7 in their build environment - only for phantomcss.

Thanks a lot!

**Comment by jamescryer** [comment]
Its fixed to 1.9.7 because of this issue. https://github.com/ariya/phantomjs/issues/12697

The next dependency bump will be to v2 hopefully!
