### ISSUE TITLE
phantomjs not available using download/install instructions

### ISSUE THREAD

**Issue by bitwombat** [Huddle/PhantomCSS#111]
Noob here.  ```npm install phantomcss``` plops everything in ~/node_modules and nothing in ~/node_modules/.bin.  Which means a bunch of binaries needed by PhantomCSS are under ```~/node_modules/phantomcss```.  So I had to do this to get it to work:

    export PATH=$PATH:/home/gbell/node_modules/phantomcss/node_modules/phantomjs/bin

and also for ```/home/gbell2/node_modules/phantomcss/node_modules/casperjs/bin```
and ```/home/gbell2/node_modules/phantomcss/node_modules/resemblejs/bin```

That looks like Doing It Wrong.  Advice?

**Comment by jamescryer** [comment]
Hard for me to say for sure.  Possibly NPM resolution, might also be something with the installation script in https://www.npmjs.com/package/phantomjs

**Comment by jamescryer** [comment]
I don't think this is resolvable here.  closing the issue
