### ISSUE TITLE
Converting spaces to underscores

### ISSUE THREAD

**Issue by asymmetric** [Huddle/PhantomCSS#112]
Currently, spaces in screenshot filenames are left as-is, which makes working with those files in git cumbersome.

Would you accept a PR for converting spaces to underscores/dashes?

**Comment by Maks3w** [comment]
This implies a BC Break.

**Comment by jamescryer** [comment]
I'll accept a PR for an optional parameter.  But you could use the `fileNameGetter` method override to change output file names.

**Comment by asymmetric** [comment]
Do you think that changing the default to using underscores/dashes would break current workflows?

Or are there other reasons not to make that the default?

**Comment by jamescryer** [comment]
People use PhantomCSS in all kinds of ways in the wild.  I'm reluctant to change default behaviors, as this would almost certainly affect someone's workflow.
