### ISSUE TITLE
Remove `^M` at end of lines

### ISSUE THREAD

**Issue by asymmetric** [Huddle/PhantomCSS#113]
On my Linux machine, `git log` shows lots of `^M` at the end of lines.

Moreover, vim detects files in this repo as being in [dos format](http://vim.wikia.com/wiki/File_format).

Considering that both Mac and Linux use the same format, would you accept a PR converting the carriage returns?

**Comment by Maks3w** [comment]
Probably a .gitattributes file should be added for line endings normalization.

**Comment by jamescryer** [comment]
I'll accept a PR for a .gitattributes file
