### ISSUE TITLE
Targeting issue with casper.scrollTo

### ISSUE THREAD

**Issue by pixelheresy** [Huddle/PhantomCSS#115]
There seems to be an issue calculating offset automatically for a selector when using casper.scrollTo. Specifically, if I scroll to the top of the selector, it is at top: 0 relative to the current view, even though it may be top: 1200 relative to the page itself. PhantomCSS appears to take the screenshot at top: 0, but in the proper dimensions otherwise [width, height, left offset]. As a result, I get a pretty cutout of the top of the page, but not the element I really want.

I wanted to know if anyone else has seen/can reproduce this? My tests require scrolling, since there is some "pop-in" and "infinite scrolling"-style changes as you scroll down the page, all of which need some testing.

It is not too big of a worry, since I have a simple utility function in my current tests, which casper.evaluate to find out what the real top/left/height/width are and take a screenshot with these coordinates, but if this is indeed an issue, I am happy to jump into the code, fiddle around, and supply a pull request.

**Comment by jamescryer** [comment]
PhantomCSS defers to casper.captureSelector, so I suspect the bug is there, perhaps with the ClientUtils.getElementBounds method.

**Comment by pixelheresy** [comment]
Will look into it a bit. I am getting around it with using `casper.evalute` to get the info from jQuery on the client page, so I am fine for now, but it would be really nice to have the whole thing working with weirdness.
