### ISSUE TITLE
PhantomCSS screenshot different than actual site

### ISSUE THREAD

**Issue by NomNomCameron** [Huddle/PhantomCSS#116]
Here is what I'm trying to take a screenshot of in phantomcss (this is what the actual website renders):
![screen shot 2015-04-20 at 10 59 34 pm](https://cloud.githubusercontent.com/assets/4634300/7246390/7d9fede8-e7b1-11e4-8f24-cd71cf9769a3.png)

And here is what phantomcss shows as the screenshot taken:

![screen shot 2015-04-20 at 10 59 13 pm](https://cloud.githubusercontent.com/assets/4634300/7246381/4b04d146-e7b1-11e4-9c38-278cc1353d0e.png)

I'm using phantomjs as the engine, I've tried specifying different resolutions for casper to no avail.

It's also not rendering linear-gradients elsewhere (and here from the looks of it)

Any idea what may be causing this?

**Comment by Maks3w** [comment]
This is a limitation on PhantomJS also you should read the advises about different rendering with different platforms or patch levels.

https://github.com/Huddle/PhantomCSS#scaling-visual-regression-testing-within-a-large-team

**Comment by NomNomCameron** [comment]
It appears that casperjs supports phantom 2.0 now?

**Comment by jamescryer** [comment]
I don't believe CasperJS fully support PhantomJS 2 yet.  SlimerJS might give you better results?

**Comment by NomNomCameron** [comment]
I'm using Slimer for now and it seems to work fine! Thanks for replying James! :smile:
