### ISSUE TITLE
PhantomCSS only selects first DOM element matching a selector

### ISSUE THREAD

**Issue by shadowfiles** [Huddle/PhantomCSS#121]
From my understanding, this is intended behavior, but is it possible to add an option for screenshotting all elements which match a selector as well if one does not exist?

**Comment by jamescryer** [comment]
Not currently, possible though. Presumably PhantomCSS would need to generate multiple screenshots, and report if the number of matched elements/screenshots had changed. Interesting feature request, I'd certainly review/accept a PR.

**Comment by CharlesCarnell** [comment]
Our situation required us needing a selector that hits all all elements of a specific selector, specifically one that could not be done using a `for` loop with an `nth-child( i )` selector.

The current solution involves adding identifiers to all elements of our selector via an evaluate function, storing the length of the total elements found, and then looping over that length using the key as an ID to select each data attribute.

```js
var elementLength = casper.evaluate(function(){
  var element = 'section.row';
  $( element ).each(function(key, value){
    $(value).attr('data-casperid', key);
  });
  return $(element).length;
});
```
```js
for( var i = 0; i < elementLength; i++ ){
  phantomcss.screenshot( '[data-casperid="' + i + '"]', 'sectionrow_x_');
}
```

**Comment by jamescryer** [comment]
Closing issue as there are workarounds
