### ISSUE TITLE
Using SlimerJS with PhantomCSS

### ISSUE THREAD

**Issue by rossPatton** [Huddle/PhantomCSS#123]
Having trouble getting this to work in the demo.

I have phantomjs, casperjs, and slimerjs all installed.

phantomjs 1.9.8
casperjs 1.1.0-beta3
slimerjs 0.9.5

I've followed the instructions on how to set up slimerjs correctly. 

When I run the following command, nothing happens:

`casperjs test  demo/testsuite.js --engine=slimerjs`

Nothing runs, there is no output whatsoever.

I want to use slimerjs so I can test webfonts, otherwise css regression testing is kind of pointless for my particular case.

**Comment by jamescryer** [comment]
It should "just work".  If you take PhantomCSS out of the equation, can you get CasperJS working with SlimerJS?

I personally had a bit of trouble setting up SlimerJS on OSX.  I seem to remember having to modify one of CasperJS's bootstrap files, but I can't remember the details.

Sorry I can't be more helpful.  Let us know if you find a solution.

**Comment by rossPatton** [comment]
I've since been able to get it to work but don't see any difference in output. Unfortunately, I can't remember exactly what I did either :) although I did a lot of poking around inside casperjs. 

I'll try to recreate the issue.

**Comment by SonniesEdge** [comment]
I had a similar problem, with PhantomCSS failing silently when I used SlimerJS as the engine. 

The only solution I eventually found was to regress the installed version of PhantomJS to 1.8.2 - at that point it started working.

**Comment by rossPatton** [comment]
My problem turned out to be a lack of solid support for flexbox / webfonts, even with slimerjs working. I ended up using webdriverio instead.

**Comment by planktonic** [comment]
Reverting phantomJS to 1.8.2 fixed it for me too (was otherwise failing silently when using slimerjs).
