### ISSUE TITLE
SlimerJS inconsistent colors in png/jpg output

### ISSUE THREAD

**Issue by aeharding** [Huddle/PhantomCSS#126]
Hey guys

I know that this really isn't a PhantomCSS issue, but I don't know where to post this, and I was hoping to get some advice.

I render screenshots of different parts of my page.

For certain colors, the png/jpg capture (I modified to source to try jpg to see if that solved my problem) is inconsistently a different shade of that color.

Below is the example. Obviously, this makes my tests automatically fail, which is a huge problem.

Which project upstream do I complain to?

AFTER:

![4_danger diff](https://cloud.githubusercontent.com/assets/2166114/8991375/dded2ed0-36bd-11e5-8c78-ec49531e1807.jpg)

BEFORE:
![4_danger](https://cloud.githubusercontent.com/assets/2166114/8991373/dde7f5fa-36bd-11e5-82db-0de3ccff4689.jpg)

DIFF:
![4_danger fail](https://cloud.githubusercontent.com/assets/2166114/8991374/dde85522-36bd-11e5-9258-e8842452e347.jpg)

Thanks!

**Comment by jamescryer** [comment]
Interesting, I have never seen this before. Could be an issue with PhantomJS, maybe local OS settings. Please let us know if you discover the root of the problem.

**Comment by aeharding** [comment]
Thanks James

For anyone curious of OS, I'm running this on Docker with this:
https://hub.docker.com/r/cmfatih/slimerjs/

**Comment by jamescryer** [comment]
Closing issue, but feel free to re-open if any more details come to light
