### ISSUE TITLE
Is this project still maintained? phantomjs2 status?

### ISSUE THREAD

**Issue by ClaudiuCreanga** [Huddle/PhantomCSS#130]
Phantomjs2 is released, are there any plans on updating this project? Casperjs 1.1.0-beta3 works well with phantomjs2 on my mac, but phantomcss does not output any failed images.

**Comment by jamescryer** [comment]
The project is still maintained, I review every fortnight, though I have been a little busy of late.

I've been holding off upgrade work until CasperJS support for PhantomJS 2.0 is official, but that is not looking likely in the near term so will be happy to investigate soon.

I'd really like to see a PR for this change, the project is opensource after all.

**Comment by jamescryer** [comment]
Similar question raised https://github.com/Huddle/PhantomCSS/issues/135
