### ISSUE TITLE
PhantomJS 2.0 and PhantomCSS

### ISSUE THREAD

**Issue by vpatton** [Huddle/PhantomCSS#133]
Is there any way we can get PhantomCSS working with Phantom 2.0?  Phantom 2.0 actually renders icons and webfonts now.  I run the tests and phantomcss takes the screenshots, but it hangs when I try to compare the images using either compareAll or compareSession.  If not, then maybe this project should be abandoned just like CasperJs (half abandoned/supported).  There's a fix that lets CasperJS run with PhantomJS 2.0 now and I've been using it.  It would be kind of rough to drop tis to try to find something else.

**Comment by vpatton** [comment]
Correction, using debug it looks like the comparison runs, but it hits the waitFor timeout.  So then you get no results and it counts it as a fail.

**Comment by jamescryer** [comment]
Just had another look, but its incredibly unstable.  I would really like to keep a viable upgrade path, I'm hoping this is a just a question of time. I'm certainly not planning on abandoning this project, but I may not have much of a choice with regard to Phantom 2 support.

**Comment by jamescryer** [comment]
Similar question https://github.com/Huddle/PhantomCSS/issues/135
