### ISSUE TITLE
Test the difference between 2 environments

### ISSUE THREAD

**Issue by Oostie** [Huddle/PhantomCSS#134]
Hi,

Is it possible to compare 2 different environments?
Like when you have changed some CSS and test your test environment against your live website?

**Comment by jamescryer** [comment]
Absolutely, you just need to ensure that the baselines have been created, and then point the tests at the new environment.  PhantomCSS doesn't manage this for you though, you'll have to lean on PhantomJS and CasperJS.

**Comment by Oostie** [comment]
Not quite what i hoped for:) 
Is it possible to take a screenshot of website1 with a screenshot of website2 in the one and the same testrun.

**Comment by jacksodj** [comment]
yes, at its core you will need to make use of this method:
// phantomcss.compareExplicit(['/dialog.diff.png', '/header.diff.png']);

and keep track of what you are downloading to where.

if you want to make a bunch of screenshots for one site.. do that as a baseline..
then do the next to a different folder..
you will want to override the file name setting to have better control, but you should be able to do that with a JSON config file.
then loop and compare.
