### ISSUE TITLE
As Casperjs is abandoned,is it safe to use PhantomCss

### ISSUE THREAD

**Issue by em-sghosh** [Huddle/PhantomCSS#135]
I am a big fan of Phantomcss. But few days ago I get to know that Casperjs abandoned. So my question is- what is the next plan ? Shall we worry about it in any case? How its gong to effect PhantomCss users? 

Rref: https://github.com/n1k0/casperjs/issues/987
https://github.com/n1k0/casperjs/issues/1299

**Comment by jamescryer** [comment]
It is very important for me and Huddle that we have a viable upgrade path whilst retaining backward compatibility.  I'm looking into decoupling the internals of this project from CasperJS; specifically, making it work as a NodeJS module for integration with [NightmareJS](https://github.com/segmentio/nightmare) (which uses Electron), I'm also considering a minimal port of CasperJS to achieve PhantomJS 2.0 support. However, my contributions are very much driven by the requirements of the Huddle web application and thus, may take some time.

I would love to see contributions, suggestions and PRs to get us there faster.

**Comment by micahgodbolt** [comment]
Really happy to hear that @jamescryer. I've been really happy with my current workflow using PhantomCSS, but the lack of PhantomJS 2.0 support has had me looking at selenium based solutions.

Will certainly keep an eye on what happens with this project in the future.

**Comment by micahgodbolt** [comment]
And from the look of nightmare and Electron, they both look like solid projects. I'd be happy to try out a fork of PhantomCSS that used that stack.

**Comment by miroamarillo** [comment]
+1

**Comment by panalbish** [comment]
+1

**Comment by conwaydev** [comment]
+1

**Comment by davidchin** [comment]
+1

**Comment by istr** [comment]
Instead of adding another +1, [I started experimenting with nightmare](https://github.com/istr/PhantomCSS/tree/feature/nightmare) yesterday. It turns out that due to the usage of "bleeding edge" stuff, nightmare itself is broken for me:
- the test suite happily "passes" (due to mocha + ES6/ES7)
- a vanilla checkout is not able to produce screenshots for me and the test suite fails nearly completely after removing the fancy new stuff

I am still investigating the root cause of my issues with nightmare.

**Comment by istr** [comment]
The root cause for nightmare not working for me seems to be a broken ```electron-prebuilt``` that nightmare is unable to detect (nightmare more or less fails silently if electron-prebuilt fails).

Apart from that some major re-working for the more sophisticated parts of casperjs (esp. restricting the screenshot to a given selector) will be needed to use nightmare or any other casperjs -> phantomjs stack replacement.

**Comment by istr** [comment]
The next thing I will try is "a minimal port of CasperJS to achieve PhantomJS 2.0 support", because:
- I think that this will be far easier to implement
- it might (hopefully) motivate other people to take over casperjs maintainance and push phantomjs 2.0 support to upstream
- it will be easier to retain backwards-compatibility for phantomcss

**Comment by jamescryer** [comment]
Thanks for the feedback.  I believe I can get PhantomCSS working with Nightmare, but a Nightmare integration won't be a swap out replacement for CasperJS; this would mean a freeze or rewrite trade-off for existing PhantomCSS/CasperJS test suites in the wild. I'm going to continue investigating Nightmare in the time I have.  CasperJS on PhantomJS 2 is still the ideal solution.

**Comment by istr** [comment]
Yes, I think that nightmare would be a nice-to-have alternative (and I am sure that I could bring that to life, too), as well as other pluggable, instrumentable browsers...

**Comment by istr** [comment]
Installing phantomjs2 through npm cross platform is *a mess*, see [phantomjs2 issues](https://github.com/zeevl/phantomjs2) and [phantomjs download page](http://phantomjs.org/download.html). It seems that phantomjs(2) development is as stuck as that of casperjs. 

For the first "minimal port" I will drop requiring phantomjs through npm at all and assume you have a running phantomjs2 binary installed and working in your path. Maybe I will search for / create a thin wrapper npm module that just checks for a working phantomjs2 later on.

**Comment by istr** [comment]
[Resurrected an old try to make casperjs work with phantomjs2](https://github.com/istr/casperjs/tree/feature/phantomjs2). Test suite nearly passing (still 5 errors left).

**Comment by istr** [comment]
And just FYI: there already is a [2.0.1 pre-release](https://github.com/skakri/phantomjs/releases/tag/2.0.1-regression-12506) that seems to fix the file input regression.

**Comment by istr** [comment]
In the meantime I prepared [a casperjs version that passes self-tests on pre-built 1.9.6, 2.0.0, 2.0.1 (Ubuntu 14.04.3)](https://github.com/istr/casperjs/tree/feature/phantomjs2). Please check if this works for you (and if you have time, if it works on slimerjs and lower phantomjs versions), too.

**Comment by Pszek** [comment]
Since Nightmare has seen lots of development over the past few months, is it easier to make it work with PhantomCSS now? @istr I looked at your branch but didn't see how to make Nightmare work with it…

**Comment by istr** [comment]
@Pszek I abandoned my nightmare experiment in favor of contributing to CasperJS and [publishing a new beta with PhantomJS 2.0 / 2.1 support](https://github.com/n1k0/casperjs/releases/tag/1.1-beta5). You might want to try my [PhantomCSS / PhantomJS 2 branch](https://github.com/istr/PhantomCSS/tree/feature/phantomjs2) and/or [my PhantomFlow / PhantomJS 2 branch](https://github.com/istr/PhantomFlow/tree/feature/phantomjs2) instead.

Integrating nightmare into PhantomCSS seems to be a lot of work at the time being.

**Comment by istr** [comment]
@jamescryer If you would like a PR for PhantomJS 2 support, I might be able to prepare something based on my branches.

**Comment by jamescryer** [comment]
@Pszek Nightmare needs to mature a little more before it becomes a viable integration target for PhantomCSS, I hit a fair few problems, specifically with regard to long running waits and EventEmitter memory leaks. An Electron integration of some sort is definitely worth investigation though.

@istr I'd certainly be happy to review any PR

**Comment by jamescryer** [comment]
I've bumped master branch to v1 which is tracking the latest CasperJS, this works with PhantomJS 2.  It's not ideal to be tracking master, but I think the benefit outweighs the risk. Upgrade went smoothly for me.

Looks like there it lots of great work going on in the CasperJS camp, as soon as they publish a stable (to PhantomCSS) release I will lock down the dependencies.
