### ISSUE TITLE
Count instances of a screenshot appearing on a page

### ISSUE THREAD

**Issue by brendonnelson** [Huddle/PhantomCSS#136]
Is it possible in PhantomCSS to take a screenshot of a WebElement, then go through a web page and count the number of times that screenshot is found on the page? For instance, taking a screenshot of a check box or a form field, then going through a page and counting the instances of that check box or form field on that page.

**Comment by jamescryer** [comment]
You can count the number of elements using CasperJS. You don't need to screenshot the elements, or count the screenshots.
