### ISSUE TITLE
How to take two screenshots in one script run, then compare those two screenshots? 

### ISSUE THREAD

**Issue by brendonnelson** [Huddle/PhantomCSS#138]
Basically, I have multiple elements on a website that should be the same. So my script takes a screenshot of one element, then clicks to go to another page, then takes a screenshot of a different element (that should be identical).

How do I get the automation to compare those two screenshots, rather than having it compare screenshots of the same element after running the script twice?

**Comment by jamescryer** [comment]
I guess you could do this by providing the same image name to two different phantomcss.screenhots.

Or use `phantomcss.compareFiles(baseFile, diffFile);` after the two baselines are created.

Though, it would be simpler if you just tested each one individually and then checked that baselines look the same - if they ever go out of sync the suite should fail.

**Comment by brendonnelson** [comment]
Is there a particular syntax that I'm missing here. Right now I'm doing

		phantomcss.compareFiles('C:\tools\PhantomCSS-master\screenshots\header\Header_Page_0.png', 'C:\tools\PhantomCSS-master\screenshots\header\Header_Other_Page_1.png');

And I get

    uncaughtError: [Exception... "Component returned failure code: 0x80004005 (N
S_ERROR_FAILURE) [nsILocalFile.isFile]"  nsresult: "0x80004005 (NS_ERROR_FAILURE
)"  location: "JS frame :: resource://slimerjs/addon-sdk/toolkit/loader.js -> re
source://slimerjs/addon-sdk/sdk/io/file.js :: isFile :: line 116"  data: no]

**Comment by jamescryer** [comment]
Looks ok to me.  I can also confirm that the compareFiles method is working ok with PhantomJS and SlimerJS on Windows.

Sorry I can't offer any more help. If you have made any progress with this issue, please update the ticket.
