### ISSUE TITLE
[Question] Small visual differences without changes

### ISSUE THREAD

**Issue by verpixelt** [Huddle/PhantomCSS#140]
Hey y'all,
we've setup PhantomCSS for our refactoring project at http://hood.ie. For now we have to take screenshots of whole pages and compare them after making changes to the Sass files.
One issue we have right now is, that sometimes I get test failures without even having changed something. We have test suites (separate files) for 3 different viewport sizes. Right now the large one fails and shows differences (0.11% - 1.46%) but we haven't changed anything.
Any ideas why this is happening?
If you want to have a look at the test suites you can find them here https://github.com/hoodiehq/hoodie-css/tree/fix/remove-nesting.
![hoodie-community--1440x900_5 1 fail](https://cloud.githubusercontent.com/assets/1640079/11397368/25791436-9379-11e5-9c43-99baa9c54628.png)

**Comment by verpixelt** [comment]
I think shortly after posting this issue and browsing through your other open issues I found what causes this problem. My setup is a mbpr and an external non-retina monitor. For some reasons the SlimerJS window, for the test suites small and medium, opened always on my mbpr screen, the large on only the first time and the second time on the non-retina screen. Unplugging the external monitor and run all the tests on my mbpr results in passing tests :)

**Comment by istr** [comment]
If running the slimerjs engine it is highly advisable to wrap it into an ```xvfb-run``` call for real headless testing. Something along the lines of [casperjs .travis.yml](https://github.com/istr/casperjs/blob/feature/phantomjs2/.travis.yml).

Another possible source of non-reproducible slight differences are non-finished CSS transitions. Use ```phantomCSS.turnOffAnimations()``` to disable these, and see [this PR](https://github.com/Huddle/PhantomCSS/pull/141) for situations where you are using webshims.

**Comment by verpixelt** [comment]
Thanks @istr. I will have a look at the `xvfb-run call`. So far the only issue affecting my tests was the above described monitor/resolution issue.
