### ISSUE TITLE
[Question] How to see selector elements of a transferred page after click?

### ISSUE THREAD

**Issue by nhufinney** [Huddle/PhantomCSS#144]
Hi Jamescryer,

After click submit button of a signup form, browser will be transferred to a login successful page. However, casperjs and phantomjs do not see selector elements of the new transferred page. It can take a screenshot of the new transferred page but cannot see its selector elements.
Would you please guide me how to set those selector elements of the new transferred page become visible?
Thank you so much.

**Comment by jamescryer** [comment]
It should be able to find the elements.  It's possibly a timing problem.  Try invoking your PhantomCSS screenshots in the callback of a `casper.wait`

**Comment by nhufinney** [comment]
Awesome. Thank you so much
