### ISSUE TITLE
Casper cant execute evaluate()

### ISSUE THREAD

**Issue by cvillanujr** [Huddle/PhantomCSS#145]
I was trying your demo and added phantomcss.turnOffAnimation() to testsuite.js below phantomcss.init() like in your example but I get this error

![cli_screenshot](https://cloud.githubusercontent.com/assets/1615958/11884831/8e33fa72-a4d1-11e5-9020-8e61009fb79d.jpg)

I'm running Win7 Pro x64.

**Comment by jamescryer** [comment]
It evaluates per page load, it should work after the `casper.start()` statement.
