### ISSUE TITLE
Elements missing from screenshot

### ISSUE THREAD

**Issue by ayoubabid** [Huddle/PhantomCSS#149]
I took a screenshot for a page, but it is missing elements (Photo). When i call the same page from a normal browser, it's there. I did't use any thing to hide the picture in the script oder something like this ... 

![bildschirmfoto 2016-01-19 um 12 01 52](https://cloud.githubusercontent.com/assets/10046630/12416927/c5d3f652-bea4-11e5-9d81-0dc4388ed8d4.png)
<img width="833" alt="bildschirmfoto 2016-01-19 um 12 03 13" src="https://cloud.githubusercontent.com/assets/10046630/12416928/c5d6f5d2-bea4-11e5-9616-760fe33b1508.png">

**Comment by jamescryer** [comment]
Hard to say.  It could be that you are using a technology that isn't supported by PhantomJS.  It might also be a broken media query - I can only guess.

Let us know if you resolve your problem.
