### ISSUE TITLE
Pages not updating in test, appear to be cached

### ISSUE THREAD

**Issue by MickeyKay** [Huddle/PhantomCSS#150]
For whatever reason, PhantomCSS doesn't seem to be picking up changes to my site. For example, I ran a test, then edited some CSS to make my nav links bold, then ran the test again. For whatever reason, the generated screenshot doesn't show any of my updates, even though manually loading the page does. Within my test file I've tried adding a URL param (e.g. `localhost.com/?asdfhkjasdhf`) as well as running `this.reload()` to force refresh the page, however no matter what I do, the screenshots don't reflect my updates.

Any idea on what might be causing this issue (caching? something else?), and how to prevent it?

Thanks!

Fantastic project!!!!

**Comment by jamescryer** [comment]
Very odd, I doubt it's a problem with PhantomCSS itself, all it does is delegate to PhantomJS's capture methods, and runs Resemble.js to compare the images.  

I would try taking PhantomCSS and maybe CasperJS out of the equation, to try and find out what is happening.

Please let us know if you solve your problem, and have any feedback.
