### ISSUE TITLE
npm vs git install routine create very different environments

### ISSUE THREAD

**Issue by pbb72** [Huddle/PhantomCSS#158]
Okay, I am sorry if this is not making any sense or completely misguided, I am very new to npm, git and PhantomCSS, but I think this should be more clear in the documentation.

It's stated you can either install ("download") through `npm install phantomcss` and `git clone git://github.com/Huddle/PhantomCSS.git` (followed by `npm install`).

The documentation does not state that this creates to very different environments, one where PhantomCSS is in `./node_modules/phantomcss/`, in the other it is in `./PhantomCSS/` (with a `./PhantomCSS/node_modules/` that does *not* contain `phantomcss/`).

This difference has quite a big impact on how the code can be used, especially when not running from the folder that is containing the `phantomcss.js` file, for example in the value of the `libraryRoot` option. The documentation also seems to switch between things that work when installed through npm, and when installed through git.

Again, this might not be an issue for those are familiar with npm etc, but it caused me quite some headaches.

**Comment by jamescryer** [comment]
Thanks

**Comment by jamescryer** [comment]
https://github.com/Huddle/PhantomCSS/pull/153 Hopefully removes the need for LibraryRoot
