### ISSUE TITLE
Resemble compare fails silently

### ISSUE THREAD

**Issue by amaschas** [Huddle/PhantomCSS#164]
I'm trying to integrate PhantomCSS into my project, and my tests were always passing, even with big differences between the generated screenshots. The screenshots were generated correctly, but the comparison was not happening correctly. After some digging, I found that the `data` arg in the `onComplete` callback on line 610 of phantomcss.js contains only `{"error":"Image load error."}`. I'm still investigating why the image fails to load, but the larger issue is that this type of failure is totally silent. Here is the code for my test:

```
var fs = require('fs'),
path = fs.absolute(fs.workingDirectory + '/PhantomCSS/phantomcss.js'),
phantomcss = require(path),
server = require('webserver').create();

var html = fs.read( fs.absolute( fs.workingDirectory + '/dist/styleguide/section-components.html' ));

server.listen(8080,function(req,res){
  res.statusCode = 200;
  res.headers = {
    'Cache': 'no-cache',
    'Content-Type': 'text/html;charset=utf-8'
  };
  res.write(html);
  res.close();
});

phantomcss.init({
  rebase: casper.cli.get('rebase'),
  casper: casper,
  addLabelToFailedImage: false,
  libraryRoot: './PhantomCSS',
});

casper.test.begin('Coffee machine visual tests', function (test) {

  casper.on('remote.message', function (msg) {
    this.echo(msg);
  });

  casper.on('error', function (err) {
    this.die("PhantomJS has errored: " + err);
  });

  casper.on('resource.error', function (err) {
    casper.log('Resource load error: ' + err, 'warning');
  });

  casper.start('http://localhost:8080');

  casper.viewport(1024, 768);

  casper.then(function () {
    phantomcss.screenshot('.m-button--small', 'm-button--small');
  });

  casper.then(function now_check_the_screenshots() {
    // compare screenshots
    phantomcss.compareAll();
  });

  /*
  Casper runs tests
  */
  casper.run(function () {
    console.log('\nTHE END.');
    casper.test.done();
  });
});
```

**Comment by jamescryer** [comment]
Thanks.  Yes it should detect an error from Resemble.js and report on that failure.

**Comment by amaschas** [comment]
Any clue why the image fails to load in this context?

**Comment by jamescryer** [comment]
It looks ok to me.  Sorry I can't be of more help. Please let us know if you fix your problem.

**Comment by Polvista** [comment]
I have the same issue with resembleJs integration.
I use SlimerJS and Firefox 48 on osx.

Here is my pantomcss config:


    phantomCss.init({

        rebase: (casper as any).cli.get( "rebase" ),

        libraryRoot: fs.absolute('node_modules/phantomcss'),

        addIteratorToImage: false,

        casper,

        screenshotRoot: fs.absolute('front/tests/screenshots/baseline'),

        failedComparisonsRoot: fs.absolute('front/tests/screenshots/failed'),

        comparisonResultRoot: fs.absolute('front/tests/screenshots/result'),

        cleanupComparisonImages: true,

        addLabelToFailedImage: false,

        mismatchTolerance: 0.05,

        prefixCount: true,

    });

All screenshots generated correctly, but resembleJS cannot compare them.
It receives `File` object from phantomcss, reads it with `FileReader` and gets base64 version of image.

And then resemble try to obtain image:

    var hiddenImage = new Image();
    hiddenImage.setAttribute("crossorigin", "anonymous");
    hiddenImage.src = event.target.result; //base64 string from FileReader

It fails without any helpfull exception.

Any thoughts what could it be?

**Comment by Polvista** [comment]
Actually, this is resembleJS problem - [https://github.com/Huddle/Resemble.js/issues/77](https://github.com/Huddle/Resemble.js/issues/77)
