### ISSUE TITLE
WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

### ISSUE THREAD

**Issue by reacher-lu** [Huddle/PhantomCSS#165]
![image](https://cloud.githubusercontent.com/assets/3804296/16543516/c8d3cede-410a-11e6-8f5b-f70f15edc57b.png)

![image](https://cloud.githubusercontent.com/assets/3804296/16543518/d3d258b4-410a-11e6-85d4-fe35b1f5bd7d.png)

I just install and running 

![image](https://cloud.githubusercontent.com/assets/3804296/16543520/e6ca4198-410a-11e6-8adf-007fd3ba820a.png)

and got this error

**Comment by jamescryer** [comment]
No repro, closing
