### ISSUE TITLE
Screenshots not always aligned with selectors

### ISSUE THREAD

**Issue by joshuamartin** [Huddle/PhantomCSS#173]
Screenshots are not always aligned with selectors - in my case the vertical alignment is not consistent - haven't tested for horizontal alignment yet.

When multiple (similar) selectors are used for a series of screenshots (on the same page) some of them line up perfectly (screenshot captures entire selector), some only partially, and some not at all. The dimensions of the screenshots are always correct, just the 'coordinates' are wrong.

Can be overcome by setting fixed heights on *all* visible elements, but that's not desirable. Anybody encountered this? or found a clean way to avoid it?

**Comment by jamescryer** [comment]
Movement on the page, e.g images being loaded in, or content being Ajaxed in could be moving those elements at just the wrong time during your test.  We see "flaky" tests a lot with application testing, and usually it's resolvable by waiting for all the content & images to load fully.

CasperJS provides two methods which are particularly useful in this case `casper.waitForSelector` & `casper.waitForSelector`

http://docs.casperjs.org/en/latest/modules/casper.html

Hope that helps.
