### ISSUE TITLE
When page has asynchronously content  following error occures.

### ISSUE THREAD

**Issue by vanBersie** [Huddle/PhantomCSS#176]
I want to take a screenshot of a page, navigation and other elements are displayed in the screenshot but the important content can't be loaded. An error occures: "Unsafe Javascript attempt to access frame with URL about:blank from frame..." and "Domains, protocols and ports must match".

Is there a workaround for that? I tried to pass settings like 'webSecurityEnabled: false' or 'ssl-protocol: "any"' within the testfile but failed. Is there any workaround for that?

**Comment by jamescryer** [comment]
I'm not aware of a solution to this, other than modify the page under test. But silencing errors like this it should be handled in PhantomJS itself, rather than PhantomCSS
