### ISSUE TITLE
Page is not loading properly some components are missing while taking the screenshots

### ISSUE THREAD

**Issue by DakshayaniChebrolu** [Huddle/PhantomCSS#179]
Page is not loading properly , some components are missing even i have made wait()

**gulp file**

_gulp.task('test', function() {
del.sync('./failures');
del.sync('./screenshots/**/.{fail.png,diff.png}');
console.log('Phantom CSS starting');
return gulp.src('test/.js')
.pipe(phantomcss({
mismatchTolerance: 2.5
}));
});_

**Casper**

_casper.start('https://erhvervselvbetjening.tdc.dk/?loginAction=start').then(function () {
this.viewport(1280, 1024);
this.wait(1000, function () {
phantomcss.screenshot('html');
});
});
casper.run();_

Please find the below screenshot taken by phantomcss where the login module is missing

![image](https://cloud.githubusercontent.com/assets/23076462/21546060/91a04424-cddc-11e6-9db0-08e5739368ef.png)

But the actual page is looking like below, having the login component

![image](https://cloud.githubusercontent.com/assets/23076462/21546068/a2c4ad08-cddc-11e6-9e2f-de8366f2d2a0.png)

Why i am unable to capture the login component. Please help me to solve this.

**Comment by DakshayaniChebrolu** [comment]
React Component code is not rendering in html.
Please find the versions 
casperjs - 1.1.3
phantomjs-prebuilt - 2.1.7
phantomcss  - 1.1.3
resemblejs - 2.2.3
gulp-phantomcss - 0.3.0

Please help me to solve this issue. why i am unable to capture the react components?

**Comment by jamescryer** [comment]
This is unlikely to be a problem with PhantomCSS. My guess is that it's a PhantomJS incompatibility with ES2016+ code in your framework, possibly a prototypal method that isn't available in PhantomJS without a shim.  I'd first try the debugging options `--verbose --log-level=debug`, then perhaps use the remote debugger http://phantomjs.org/troubleshooting.html..  Also worth checking your site in an older IE browser, like IE9 & 10, as they tend to exhibit the same problems

**Comment by DakshayaniChebrolu** [comment]
Hi james
Thanks for your comment.
I am getiing an error like
Error: ReferenceError: **Can't find variable: Audio**
My page is having a Audio component which is not recognised by phantomjs. 
Do you know any woraround for this?
Thanks in advance.

**Comment by jamescryer** [comment]
I think the only option you have is to test for `Audio` as a browser feature, in your application code, and degrade gracefully if it is not available. At it's simplest that might be a `try {} catch(e){ }`
