### ISSUE TITLE
xunit testcase name inconsistent and not inherited from casperjs

### ISSUE THREAD

**Issue by bitcoder** [Huddle/PhantomCSS#182]
The JUnit XML report created by CasperJS+PhantomCSS is inconsistent in the naming of testcases.
The output of phantomCSS evaluation goes to the name of the testcase within the XML report.

```
<testcase name="No changes found for screenshot /Users/smsf/PhantomCSS/screenshots/open coffee machine button_0.png" classname="demo/testsuite" time="0.129"/>
```

If the same test fails, the testcase is named in other way:

```
<testcase name="Visual change found for screenshot /Users/smsf/PhantomCSS/screenshots/coffee machine dialog_1.png (10.72% mismatch)" classname="demo/testsuite" time="0.442"><failure type="fail"><![CDATA[Visual change found for screenshot /Users/smsf/PhantomCSS/screenshots/coffee machine dialog_1.png (10.72% mismatch)]]></failure></testcase>
```

The problem seems that PhantomCSS is not explicitly naming the testcases

```
function _onPass( test ) {
        console.log( 'PPPPPPPPPPPPPP\n' );
        console.log( JSON.stringify(test) );
        casper.test.pass( 'No changes found for screenshot ' + test.filename,  {name: test.name} );
}

function _onFail( test ) {
        console.log( 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' );
        console.log( test );
        casper.test.fail( 'Visual change found for screenshot ' + test.filename + ' (' + test.mismatch + '% mismatch)', {name: test.name});
}

function _onTimeout( test ) {
        console.log( '\n' );
        casper.test.info( 'Could not complete image comparison for ' + test.filename );
}

function _onNewImage( test ) {
        console.log( '\n' );
        casper.test.info( 'New screenshot at ' + test.filename );
}
```

As mentioned in CasperJS documentation (http://docs.casperjs.org/en/latest/testing.html), it's possible to name a testcase explicitly as seen bellow.

```
casper.test.fail('google search for "casperjs" retrieves 10 or more results', {name: 'result count is 10+'});
```

However, it seems that the "test" object received by the PhantomCSS callbacks don't have access to the casperJS message argument that can be passed to the assertions.
The testcases names should be consistent, and my suggestion which is the approach followed by casperjs, is to use the optional "message" argument to the assert statements as the name of the Xunit testcase.

This can easily be verified using PhantomCSS's sample demo and requesting the xunit XML report:

`casperjs test demo/testsuite.js  --xunit=x.xml`

**Comment by jamescryer** [comment]
It can't pass more context to the test, as the assertion happens after the actual test execution.  But I made the following change to ensure that the testname is always the same whilst preserving decent messaging on the command line.  You can of course override those callbacks for your own purposes. 


```
function _onPass( test ) {
	console.log( '\n' );
	var name = 'Should look the same ' + test.filename;
	casper.test.pass(name, {name: name});
}

function _onFail( test ) {
	console.log('\n');
	var name = 'Should look the same ' + test.filename;
	casper.test.fail(name, {name:name, message: 'Looks different (' + test.mismatch + '% mismatch) ' + test.failFile });
}
```

**Comment by bitcoder** [comment]
Hi @jamescryer,
thanks for your feedback. 
Your solution works and seems reasonable so I kindly ask you to consider it both for the v0 and master branches.
By the way, we here at "Xpand add-ons" will be referring PhantomCSS from a tutorial that we are going to provide for our test management tool for JIRA: [Xray for JIRA](https://marketplace.atlassian.com/plugins/com.xpandit.plugins.xray/server/overview).
Many thanks.

**Comment by jamescryer** [comment]
I don't have the time to maintain the v0 branch; I recommend everyone to update to v1/master.

Thanks

**Comment by bitcoder** [comment]
Ok but the v1/master branch is giving errors if you try to run the demo/testsuite :(
