### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'fileData.data')

### ISSUE THREAD

**Issue by romulorochabr** [Huddle/PhantomCSS#183]
Hi guys, I am trying to use PhantomCSS first time. Im following the given step-by-step. It runs very well first time and generates the screen shots, but the second time I receive the erro: TypeError: undefined is not an object (evaluating 'fileData.data'). 

I took a look at the code and its not "upload or using the files". 

Any ideas how to fix it or make it works?

Thank u in advance.
[log.txt](https://github.com/Huddle/PhantomCSS/files/778517/log.txt)

**Comment by kosz85** [comment]
And what was the cause? I have similar problem and I'm struggling.

**Comment by romulorochabr** [comment]
Hi mate, I think I had a similar problem than yours but I cannot remember very well what my problem was.
