### ISSUE TITLE
screenshot passes on if selector is missing

### ISSUE THREAD

**Issue by MartinNowak** [Huddle/PhantomCSS#188]
While a warning is printed to the console, the command itself does not fail, so the casparjs test will continue and the final compareAll succeeds. Not a particularly useful behaviour for CI usage.
https://github.com/Huddle/PhantomCSS/blob/6b96c9ee44762097bad017f7e62ecf9009285ca0/phantomcss.js#L315

In general the checking is a bit loose, e.g. a non-existing path for compareExplicit will add a passing test rather than a failing one.

**Comment by jamescryer** [comment]
Yes, perhaps a "failOnError" option.  Happy to review a Pull Request.

**Comment by jamescryer** [comment]
Fixed with PR #197, released in v1.2.0
