### ISSUE TITLE
Bug scroll bottom on fail screenshot

### ISSUE THREAD

**Issue by jeffbiondi** [Huddle/PhantomCSS#195]
Hello

PhantomCSS generates the following screenshots : 
![dev__header_full_ fail](https://user-images.githubusercontent.com/6355043/30381689-6825bc1e-989d-11e7-8a87-e15f69ed8583.png)

Instead of the normal header screenshot
![dev__header_full_](https://user-images.githubusercontent.com/6355043/30381728-890fc3fc-989d-11e7-9cc4-607fc1169002.png)

It's like a scroll to bottom before the failure png creation.
Is there a trick to fix that issue ?

Thanks,
JF.

**Comment by jamescryer** [comment]
Movement created by animations/transitions or changing markup can cause problems like this. 

* Make sure your images have fixed width and height applied, either inline or through CSS. 
* Invoke `phantomcss.turnOffAnimations();` before running the tests
* Use CasperJSs wait methods before your visual tests http://docs.casperjs.org/en/latest/modules/casper.html#waitforselector

Hope that helps

**Comment by jeffbiondi** [comment]
It's only on fail screen. Every fail screen have a kind of translate Y of 30px.  Base and Diff are good.

**Comment by jamescryer** [comment]
Not sure If I can help further, let us know if you resolved your problem.
