### ISSUE TITLE
Support for the https pages

### ISSUE THREAD

**Issue by PramodDutta** [Huddle/PhantomCSS#196]
Right now, We have some Testapp which have an invalid cert of ssl. I can't run the suite even with the option
 > casperjs test test/test1.js --ignore-ssl-errors=true --ssl-protocol=any
it does not work.

**Comment by jamescryer** [comment]
Not sure if any of these options will help http://phantomjs.org/api/command-line.html

Closing the ticket as not directly relating to the project.
