### ISSUE TITLE
Allow option. asyncCompareTimeout

### ISSUE THREAD

**Issue by roblevintennis** [Huddle/PhantomCSS#89]
We'd really like to expose the timeout that's currently hard-coded here: https://github.com/Huddle/PhantomCSS/blob/5f85b471e1a8ab8aff6f7ec3917595fd423163f6/phantomcss.js#L399 to 10 seconds via a new `option. asyncCompareTimeout` since, for certain CI environments, >10seconds may be tolerable and allow for larger screenshots. I know the guidelines specify against large screenshots, but it seems reasonable to expose control of the timeout used.

**Comment by jamescryer** [comment]
Closed by https://github.com/Huddle/PhantomCSS/pull/93 with options.waitTimeout
