### ISSUE TITLE
Fail and diff ouput files

### ISSUE THREAD

**Issue by superalex** [Huddle/PhantomCSS#90]
Hello!,

I think output files have changed filenames. If a test is failing I would expect to see the new screenshot in the .fail.png file and the diff one in the .diff.png. Actually it's working in the opposite way...

Regards

**Comment by asymmetric** [comment]
I agree that it's pretty confusing at the moment. Both @superalex 's naming scheme and @jamescryer would be an improvement.

**Comment by jamescryer** [comment]
Was fixed with the introduction of the following options

```
var options = {
  baselineImageSuffix:  "",
  diffImageSuffix: ".diff",
  failureImageSuffix: ".fail"
};
```

**Comment by rlamorea** [comment]
I don't think this provides a valid workaround.

If I change diffImageSuffix to _anything_ other than `.diff`, it seems like phantomcss just starts capturing new images every time I execute.

I would also argue (pretty strongly) that @superalex is correct, and that even if there is an impact to existing usages, a `.diff` file should mean the diff, and a `.fail` file should mean the failed screencap.  To argue that "it was always wrong" doesn't mean that it isn't still a bug that should be fixed.
