### ISSUE TITLE
Get PhantomCSS to work with Travis

### ISSUE THREAD

**Issue by amitaibu** [Huddle/PhantomCSS#92]
Issue is actually a "Public service announcement" ;)

we have created a yo generator that scaffolds apps that also include PhantomCSS, and adds an integration to Travis.

A nice thing we've added is the possibility to upload images of failed tests from Travis to a public image, which really helps debugging.

http://www.gizra.com/content/phantomcss-ui-regression/

**Comment by jamescryer** [comment]
Great stuff, thanks!
