### ISSUE TITLE
Failures folder is not created and no pixels are colored to indicate a difference between screenshoots 

### ISSUE THREAD

**Issue by dacob** [Huddle/PhantomCSS#94]
Hi all,

I have installed phantomcss, phantomjs and casperjs in Windows 7 machine manually.

After that, I have tried to run demo/testsuite.js test and, when I run first, the screenshots are saved properly, but, once I have modified coffeemachine.html in order to check how differences are shown in failures folder in next test execution, neither nor "Failures" folder is created nor images are shown with Fuchsia color in order to hightlight the difference.

Is this issue related to Windows environment?

Regards and thanks in advance,

**Comment by jamescryer** [comment]
I'm not aware of any OS environment issues.  Can you check that the libraryRoot is set to the location of PhantomCSS

https://github.com/Huddle/PhantomCSS#options-and-setup

**Comment by dacob** [comment]
Hi James,

Thanks for your response.

At the beggining I had configuration by default, and then I include libraryRoot as you propose. Results are similar (first screenshot appears, but second execution fails without creating the failures folder, however _diff pictures are created in both cases):

phantomcss.init({
	failedComparisonsRoot: 'failures',
	libraryRoot: 'C:\PhantomCSS',
	screenshotRoot: 'screenshots'
});

where C:\PhantomCSS is the folder where phantomcss.js is located.

Any suggestion?

Thanks a lot

**Comment by jamescryer** [comment]
It sounds a lot like it's not finding the resemblejscontainer.html which is found in /PhantomCSS.  Can't say what the problem is though.

Let us know if you figure it out.

**Comment by dacob** [comment]
By PhantomCSS do you mean my root folder (C:\PhantomCSS)? I unziped the phantomjs-x.y.z-windows.zip into C:\PhantomCSS where is located phantomcss.js and resemblejscontainer.html.

I got: 
[PhantomCSS] Can't find Resemble container. Perhaps the library root is mis configured. (C:PhantomCSS\resemblejscontainer.html)

which is weird since I actually have resemblejscontainer.html in that specific folder.

**Comment by dacob** [comment]
Actually, I copy/paste the full Error trace if it can be helpful:

[PhantomCSS] Can't find Resemble container. Perhaps the library root is mis configured. (C:PhantomCSS\resemblejscontainer.html)
TypeError: 'undefined' is not an object (evaluating 'test.success')
  C:/PhantomCSS/phantomcss.js:435

**Comment by jamescryer** [comment]
This should work out of the box.  I'd recommend using Bower or NPM.  But PhantomJS, Casper and Resemble are all bundled inside the repo. 

If you git clone, then call `casperjs test demo/testsuite.js` from the command line, in the PhantomCSS folder - then it should all just work.  If you did use NPM, did you also run NPM install ?

**Comment by dacob** [comment]
I installed again by using git clone and it works out of the box.

Thanks a lot
