### ISSUE TITLE
Feature request: add a flag or command to force initial source screenshots regeneration

### ISSUE THREAD

**Issue by sergesemashko** [Huddle/PhantomCSS#95]
Hi,

It would be great to have something that will regenerate source screenshots from command line out of the box, like ```casperjs reference test.js```.

It's possible to force source screenshots regeneration only by deleting them manually or using Node.js in test. 

Sergey

**Comment by jamescryer** [comment]
Thanks for the suggestion. I've added an option, you can use that with casper.cli.get("reference")  for `casperjs test testfile.js --reference`.  Take a look at the demo test suite for a clearer idea.
