### ISSUE TITLE
function compareFiles issue

### ISSUE THREAD

**Issue by damirpasa** [Huddle/PhantomCSS#98]
After phantomjs upgrading (2.0) function compareFiles doesn't compare my .png files. 

I also tried to run demo test and i get an uncaughtError:

FAIL TypeError: Attempted to assign to readonly property.
    type: uncaughtError
    file: demo/testsuite.js:1966
    error: Attempted to assign to readonly property.
           	at 
           	at 
           	at 
           	at 
           	at 
           	at 
           	at [native code]
           	at 
           	at demo/testsuite.js:93:19
           	at 
    stack: not provided

After downgrade of phantomjs to 1.9.8 everything works ok. Since we have a lot of flexbox css on our pages, version 2.0 is needed to make screenshots, otherwise they are almost empty... I'd really appreciate help here..
BR, Damir

**Comment by jamescryer** [comment]
I'm holding back on PhantomJS 2 support until 2.1, partly because I don't have the time right now.  I'll accept a PR of course.

**Comment by lifeart** [comment]
I think this is solution: https://github.com/Huddle/PhantomCSS/pull/148
